name: $(Date:yyyyMMdd)$(Rev:-r)
pool:
  vmImage: 'Ubuntu 16.04'

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@1
  inputs:
    command: 'build' 
    projects: '**/*.csproj'
    arguments: '--configuration $(BuildConfiguration)'
    
- task: DotNetCoreCLI@2
  displayName: Publish
  inputs:
    command: publish
    projects: '**/*.csproj'
    publishWebProjects: false
    arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'
    zipAfterPublish: True
    modifyOutputPath: True
    includeNuGetOrg: True

- task: PublishBuildArtifacts@1
  inputs:
    artifactName: 'Release'
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
